### ISSUE TITLE
gcp-service-discovery is crashing in sandbox in prometheus deployment.

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/gcp-service-discovery#7]
Failures in sandbox -- not present in mlab-oti -- unclear what the difference is yet.

```
$ kubectl logs -c service-discovery prometheus-server-2691985596-ctmrh
2018/02/05 21:12:30 Starting a new round at: 2018-02-05 21:12:30.34286043 +0000 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6fb206]

goroutine 1 [running]:
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).getLabels(0xc4205e4f00, 0xc420748620, 0xc4203f0d20, 0xc42059e360, 0xc420000101)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:165 +0x56
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).handleInstances(0xc4205e4f00, 0xc4202ef880, 0xc420748620, 0xc4203f0d20, 0xc4202ef880, 0xc42001a190)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:236 +0x132
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).handleVersions.func1(0xc4202ef880, 0x0, 0x0)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:211 +0x49
google.golang.org/api/appengine/v1.(*AppsServicesVersionsInstancesListCall).Pages(0xc4207efa90, 0x0, 0x0, 0xc4207efa70, 0x0, 0x0)
        /go/src/google.golang.org/api/appengine/v1/appengine-gen.go:6084 +0x128
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).handleVersions(0xc4205e4f00, 0xc4202ef420, 0xc420748620, 0xc4202ef420, 0xc42001a140)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:212 +0x2c1
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).Collect.func1.1(0xc4202ef420, 0x0, 0x0)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:127 +0x40
google.golang.org/api/appengine/v1.(*AppsServicesVersionsListCall).Pages(0xc4207efc58, 0x0, 0x0, 0xc4207efc40, 0x0, 0x0)
        /go/src/google.golang.org/api/appengine/v1/appengine-gen.go:5192 +0x128
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).Collect.func1(0xc42005a770, 0x0, 0x0)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:128 +0x1cb
google.golang.org/api/appengine/v1.(*AppsServicesListCall).Pages(0xc4207efd98, 0x0, 0x0, 0xc4207efd88, 0x0, 0x0)
        /go/src/google.golang.org/api/appengine/v1/appengine-gen.go:4324 +0x128
github.com/m-lab/gcp-service-discovery/aeflex.(*Source).Collect(0xc4205e4f00, 0x2082500, 0xc4205e4f00)
        /go/src/github.com/m-lab/gcp-service-discovery/aeflex/aeflex.go:134 +0x16e
main.main()
        /go/src/gcp_service_discovery/main.go:96 +0x6eb
```

**Comment by stephen-soltesz** [comment]
Fixed by - https://github.com/m-lab/gcp-service-discovery/pull/8
